name: PoaLib
version: 2
main: poa.poalib.PoaLib
api-version: 1.19
softdepend:
  - WorldGuard
  - LuckPerms
  - Vault
  - EconomyShopGUI-Premium
commands:
  poalibtestcommand:
      permission: poa.libtestcommand